### ISSUE TITLE
how to get the stream in udp ip

### ISSUE THREAD

**Issue by sachin0606** [edporras/sigen#1]
hi, 

thanks for the code. 

its builded successfully. but not able to get stream in UDP ip to mux in the QAM. please help me to do this. 

thanks..

**Comment by edporras** [comment]
I'm so sorry but I can't. IIRC, we used to use a different tool to do this but I don't have the source. I also haven't worked on this in a while, left the broadcast industry 6 years ago, and -- most importantly -- just don't have the time. 😞

**Comment by sachin0606** [comment]
oh! but anyway.. written gre8 code.. wanted PSI/SI tool so .. if any please let me know..
