### ISSUE TITLE
Add descriptors by bit/hex value (no data structure)

### ISSUE THREAD

**Issue by nicktencate** [edporras/sigen#2]
It would be great if we could add descriptors purely by filling in the expected hex value(s) instead of having to define them in data structures. This would allow easy bit-wise cloning / modelling of other feeds and testing a device (tuner)'s response.

Something along the lines of:

ts.addHexDescriptor(0x...);

**Comment by edporras** [comment]
I don't have an easy way to add it directly to the TS as there's no way to inject it at a specific position in the section data but it'll be easy to implement using the `addDescriptor()` methods already available for the tables. I'm thinking something along the lines of `ClonedBinaryDesc` that takes a data vector argument.

I'll take care of this for you this week.

**Comment by edporras** [comment]
hi, I'm pushing a release now. Check out the example in the tests directory to see how to use it:

https://github.com/edporras/sigen/blob/master/tests/other_test.cc#L24-L44

The constructor expects a sequence that includes the tag and length bytes. It will throw a `std::out_of_range` exception if there are more than 255 bytes in the initializer list or if the second byte (the descriptor length byte) doesn't correspond to the length.

Hope this works for you.
